In [10]:
# 2.3.1 여러 가지 배열
import numpy as np

a = np.array([1, 5, 0, -1])
b = np.ones((2, 2, 2))
c = np.zeros((2, 3))
d = np.arange(10)
e = np.linspace(0, 10, 5)
f = np.random.randint(2, 10, 5)

for i in [a, b, c, d, e, f]:
  print(i, end = "\n \n \n")

[ 1  5  0 -1]
 
 
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
 
 
[[0. 0. 0.]
 [0. 0. 0.]]
 
 
[0 1 2 3 4 5 6 7 8 9]
 
 
[ 0.   2.5  5.   7.5 10. ]
 
 
[7 8 4 4 3]
 
 


In [11]:
# 2.3.2 배열의 크기와 변환
c.shape

(2, 3)

In [12]:
len(c)

2

In [13]:
c.ndim

2

In [14]:
c.dtype

dtype('float64')

In [15]:
c.reshape(1,6)

array([[0., 0., 0., 0., 0., 0.]])

In [16]:
c.astype('int')

array([[0, 0, 0],
       [0, 0, 0]])

In [17]:
d.shape

(10,)

In [18]:
d1 = d.reshape(2,5)
d1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
d1.shape

(2, 5)

In [20]:
d1.ravel()    # 배열을 행 순서로 이어 붙여 1차원 배열로 변환

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
d1[0]

array([0, 1, 2, 3, 4])

In [22]:
d1[1]

array([5, 6, 7, 8, 9])

In [23]:
d1[0][2]

2

In [24]:
d1[0,2]

2

In [25]:
d1[0, 2:4]

array([2, 3])

In [26]:
d1[0, :2]

array([0, 1])

In [27]:
d1[-1, 3]

8

In [28]:
# 2.3.3 조건문을 이용한 인덱스 검색
mu = 0
sigma = 1
arr = np.random.normal(mu, sigma, (5,3))    # 평균 0, 표준편차 1인 정규분표를 따르는 5행 3열 배열
arr

array([[-0.04998729, -3.09837162,  1.13550057],
       [ 0.26116901,  0.07935438,  1.17614973],
       [ 0.01359489, -0.60939595,  0.18444863],
       [-1.14326416, -0.43256692, -0.0085043 ],
       [-0.39821112,  1.18922148,  0.91034041]])

In [29]:
np.where(abs(arr) > sigma, "out", "in")    # 조건 만족시 out, 아니면 in

array([['in', 'out', 'out'],
       ['in', 'in', 'out'],
       ['in', 'in', 'in'],
       ['out', 'in', 'in'],
       ['in', 'out', 'in']], dtype='<U3')

In [31]:
np.where(abs(arr) > sigma)    # 행에 대한 인덱스, 열에 대한 인덱스

(array([0, 0, 1, 3, 4]), array([1, 2, 2, 0, 1]))

In [32]:
# 2.3.4 배열의 기본 연산
a = np.array([[1,3], [0,-1]])
b = np.random.randint(0,10,4).reshape(2,2)
a + b

array([[3, 5],
       [3, 3]])

In [33]:
a, b

(array([[ 1,  3],
        [ 0, -1]]), array([[2, 2],
        [3, 4]]))

In [34]:
a * b

array([[ 2,  6],
       [ 0, -4]])

In [35]:
a ** b

array([[1, 9],
       [0, 1]])

In [36]:
2 * a

array([[ 2,  6],
       [ 0, -2]])

In [37]:
a - 1

array([[ 0,  2],
       [-1, -2]])

In [38]:
np.matmul(a, b)    # 행렬의 곱 연산

array([[11, 14],
       [-3, -4]])

In [39]:
# 2.3.5 배열의 병합
np.concatenate([a, b], axis = 0)

array([[ 1,  3],
       [ 0, -1],
       [ 2,  2],
       [ 3,  4]])

In [40]:
np.concatenate([a, b], axis = 1)

array([[ 1,  3,  2,  2],
       [ 0, -1,  3,  4]])

In [41]:
np.vstack((a,b))

array([[ 1,  3],
       [ 0, -1],
       [ 2,  2],
       [ 3,  4]])

In [43]:
np.hstack((a,b))

array([[ 1,  3,  2,  2],
       [ 0, -1,  3,  4]])

In [44]:
# 2.3.6 다양한 계산 함수
des = [np.sum(a), np.mean(a), np.std(a), np.max(a), np.min(a)]
print(des)

[3, 0.75, 1.479019945774904, 3, -1]
