In [25]:
# Tensor 텐서: 파이토치의 기본 단위, GPU 연산을 가능하게 하고 Numpy 배열과 유사

In [26]:
# 4.1.1
import torch
import numpy as np

x = torch.empty(5,4)
print(x)

tensor([[4.9650e-35, 0.0000e+00, 7.0065e-44, 7.0065e-44],
        [6.3058e-44, 6.7262e-44, 7.4269e-44, 6.3058e-44],
        [6.8664e-44, 7.4269e-44, 1.1771e-43, 6.8664e-44],
        [7.0065e-44, 8.1275e-44, 6.7262e-44, 7.1466e-44],
        [8.1275e-44, 6.7262e-44, 7.8473e-44, 6.4460e-44]])


In [27]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [28]:
torch.zeros(2)

tensor([0., 0.])

In [29]:
torch.rand(5,6)

tensor([[0.2794, 0.3192, 0.0683, 0.2469, 0.5069, 0.3313],
        [0.4776, 0.3345, 0.8773, 0.7668, 0.6838, 0.6292],
        [0.0681, 0.0591, 0.6695, 0.5303, 0.6437, 0.5220],
        [0.7418, 0.2929, 0.6363, 0.9776, 0.8964, 0.7269],
        [0.4240, 0.3979, 0.8107, 0.1928, 0.5390, 0.5084]])

In [30]:
# 4.1.2 list, numpy 배열을 tensor로 만들기
l = [13, 4]    # 리스트 생성
r = np.array([4, 56, 7])
torch.tensor(l)

tensor([13,  4])

In [31]:
torch.tensor(r)

tensor([ 4, 56,  7])

In [32]:
# 4.1.3 tensor의 크기, 타입, 연산
x

tensor([[4.9650e-35, 0.0000e+00, 7.0065e-44, 7.0065e-44],
        [6.3058e-44, 6.7262e-44, 7.4269e-44, 6.3058e-44],
        [6.8664e-44, 7.4269e-44, 1.1771e-43, 6.8664e-44],
        [7.0065e-44, 8.1275e-44, 6.7262e-44, 7.1466e-44],
        [8.1275e-44, 6.7262e-44, 7.8473e-44, 6.4460e-44]])

In [33]:
x.size()

torch.Size([5, 4])

In [34]:
x.size()[1]

4

In [35]:
type(x)

torch.Tensor

In [36]:
x = torch.rand(2,2)
y = torch.rand(2,2)
x+y

tensor([[0.6225, 1.2039],
        [0.8680, 1.6667]])

In [37]:
torch.add(x,y)

tensor([[0.6225, 1.2039],
        [0.8680, 1.6667]])

In [38]:
y.add(x)

tensor([[0.6225, 1.2039],
        [0.8680, 1.6667]])

In [39]:
y.add_(x)
y    # in-place 방식으로 기존 값을 덮어 씌움

tensor([[0.6225, 1.2039],
        [0.8680, 1.6667]])

In [40]:
# 4.1.4 Tensor 크기 변환

x = torch.rand(8,8)
print(x.size())

torch.Size([8, 8])


In [41]:
a = x.view(64)    # 크기를 바꿔주는 view -> 64개 일렬로
print(a.size())

torch.Size([64])


In [42]:
b = x.view(-1, 4, 4)    # -1은 원래 크기(8*8)이 되게 하는 값이므로 4가 할당
print(b.size())

torch.Size([4, 4, 4])


In [43]:
# 4.1.5 tensor에서 numpy 배열로
x = torch.rand(8,8)
y = x.numpy()
type(y)

numpy.ndarray

In [44]:
# 4.1.6 단일 tensor에서 값으로 반환
x = torch.ones(1)
print(x.item())

1.0
